### ISSUE TITLE
Users can not get a list of most active users

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub-modules-mostactiveusers#2]
All users **except administrator** can not get a list of users.
![issue_mostactive](https://cloud.githubusercontent.com/assets/3394915/6260471/9ee2866e-b822-11e4-8e10-073d0c7bd508.png)

**Report:**

exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/protected/vendors/yii/web/auth/CAccessControlFilter.php:182 Stack trace: #0 /var/www/html/protected/vendors/yii/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), 'You are not aut...') #1 /var/www/html/protected/vendors/yii/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain)) #2 /var/www/html/protected/vendors/yii/web/CController.php(1145): CFilter->filter(Object(CFilterChain)) #3 /var/www/html/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain)) #4 /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain)) #5 /var/www/html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #6 /var/www/html/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array) #7 /var/www/html/protected/vendors/yii/web/CWebApplication.php(282): CController->run('list') #8 /var/www/html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mostactiveusers...') #9 /var/www/html/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #10 /var/www/html/index.php(39): CApplication->run() #11 {main} REQUEST_URI=/mostactiveusers/mostActiveUsers/list?CSRF_TOKEN=768688ed802cc0f219c0c45ff2e01e9b10de3d78&_=1424308742983 HTTP_REFERER=http://192.168.0.112/dashboard ---

**Comment by Vatarus** [comment]
Sorry, I have not looked access control rules.
Close the ticket.
